DROP TABLE IF EXISTS votes_journal;
DROP TABLE IF EXISTS events_journal;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS transaction_journal;
DROP TABLE IF EXISTS Votes ;
